-- Badminton App schema (v2)
-- Mirrors the AppSheet "RFC Sat" app's tables (Sessions, Games, PlayerSessions, Home),
-- rebuilt as a proper relational schema instead of a Google Sheet.
--
-- v2 correction: the real fee model was reverse-engineered from actual historical
-- data (the "Queuing sat" Google Sheet export), which revealed two things v1 got
-- wrong:
--   1. Court/shuttle rates are set PER SESSION (court rental hours x hourly rate,
--      shuttle tube cost split across shuttles and then across a 4-player game),
--      not a single global rate in app_settings.
--   2. "Payable" is not simply CourtShare + ShuttleShare. It's rounded up with a
--      buffer: Payable = ceil((CourtShare + ShuttleShare) / 10) * 10 + 10. This
--      was verified against all 383 historical PlayerSessions rows with zero
--      mismatches, so it's encoded as the generated column formula below.
--   3. "Payment" in the source data is the METHOD used (Cash / Gcash), not a
--      plain paid/unpaid flag.
--
-- Run this in the Supabase SQL editor (or `supabase db push` once you have the CLI set up).

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- players
-- New table (AppSheet stored player names as free text). Having a real table
-- lets us keep a stable roster instead of re-typing names every session.
-- ---------------------------------------------------------------------------
create table if not exists players (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- sessions   (was: AppSheet "Sessions" table)
-- One row per game day. Court/shuttle costs are set here per session (they
-- varied week to week in the historical data — different hours, different
-- rates) and shared out across whoever shows up that day.
-- ---------------------------------------------------------------------------
create table if not exists sessions (
  id uuid primary key default gen_random_uuid(),
  session_date date not null,
  title text,
  status text not null default 'Open' check (status in ('Open', 'Closed')),
  -- 6-digit code players enter on the public /join page to request a spot
  -- in this session — generated by createSession, not by the database, so
  -- it's easy to retry on a collision. Nullable only so old rows (created
  -- before this existed) don't break; every new session gets one.
  join_code text unique,

  hours numeric(5, 2) not null default 0,
  fee_per_hour numeric(10, 2) not null default 0,
  court_fee numeric(10, 2) generated always as (hours * fee_per_hour) stored,

  shuttle_tube_cost numeric(10, 2) not null default 0,
  shuttles_per_tube integer not null default 12,
  cost_per_shuttle numeric(10, 2) generated always as (
    case when shuttles_per_tube = 0 then 0 else shuttle_tube_cost / shuttles_per_tube end
  ) stored,
  -- one shuttle is shared by a 4-player doubles game
  shuttle_fee_per_game numeric(10, 2) generated always as (
    case when shuttles_per_tube = 0 then 0 else shuttle_tube_cost / shuttles_per_tube / 4 end
  ) stored,

  -- how many distinct players showed up this session; court cost is split evenly across them
  player_count integer not null default 0,
  court_share_per_player numeric(10, 2) generated always as (
    case when player_count = 0 then 0 else (hours * fee_per_hour) / player_count end
  ) stored,

  created_at timestamptz not null default now()
);

-- safe to re-run against a database created before join_code existed
alter table sessions add column if not exists join_code text;
alter table sessions drop constraint if exists sessions_join_code_key;
alter table sessions add constraint sessions_join_code_key unique (join_code);

-- ---------------------------------------------------------------------------
-- games   (was: AppSheet "Games" table)
-- One row per individual game (doubles: 4 players) within a session.
-- ---------------------------------------------------------------------------
create table if not exists games (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  game_number integer not null,
  game_date date not null,
  -- 'Requested' = submitted by a player from the public /join page, not yet
  -- approved by the queue master — see "Public game requests" below.
  status text not null default 'Queued' check (status in ('Requested', 'Queued', 'Ongoing', 'Done')),
  player1_id uuid references players(id),
  player2_id uuid references players(id),
  player3_id uuid references players(id),
  player4_id uuid references players(id),
  -- 'team1' = player1+player2, 'team2' = player3+player4, matching the
  -- CourtBox left/right split. Null = no winner recorded (optional — most
  -- games don't need one to keep the queue moving).
  winner_team text check (winner_team is null or winner_team in ('team1', 'team2')),
  score1 integer,
  score2 integer,
  -- Free-text name a player typed in on the public /join "Request a set"
  -- form (see request_game below) — who to credit/ask when the queue master
  -- reviews it. Null for every game logged the normal way (queue master's
  -- own New Game / Edit Game forms never set this).
  requested_by text,
  -- An opaque per-device id (crypto.randomUUID(), generated client-side and
  -- kept in localStorage — see JoinForm.tsx), stored on a "Requested" row
  -- so /join's queue view can show a player only THEIR OWN pending
  -- requests instead of everyone's (get_queue_by_code below scopes on it).
  -- Deliberately not the same thing as requested_by: that's a free-text
  -- name the player may not have bothered typing, this is generated
  -- automatically regardless. Never shown to anyone, including the queue
  -- master — purely a filter key.
  requester_token text,
  created_at timestamptz not null default now(),
  unique (session_id, game_number)
);

-- safe to re-run against a database created before "Ongoing" existed
alter table games drop constraint if exists games_status_check;
alter table games add constraint games_status_check check (status in ('Requested', 'Queued', 'Ongoing', 'Done'));

-- safe to re-run against a database created before requested_by existed
alter table games add column if not exists requested_by text;

-- safe to re-run against a database created before requester_token existed
alter table games add column if not exists requester_token text;

-- safe to re-run against a database created before winner/score existed
alter table games add column if not exists winner_team text;
alter table games drop constraint if exists games_winner_team_check;
alter table games add constraint games_winner_team_check check (winner_team is null or winner_team in ('team1', 'team2'));
alter table games add column if not exists score1 integer;
alter table games add column if not exists score2 integer;

-- ---------------------------------------------------------------------------
-- player_sessions   (was: AppSheet "PlayerSessions" table)
-- One row per player per session: how many games they played and what they owe.
-- court_share is that session's court_share_per_player (constant per player for
-- the day); shuttle_share scales with how many games they actually played.
-- ---------------------------------------------------------------------------
create table if not exists player_sessions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  player_id uuid not null references players(id),
  total_games integer not null default 0,
  court_share numeric(10, 2) not null default 0,
  shuttle_share numeric(10, 2) not null default 0,
  -- Queue-master-set discount for this player, this session (kids, guests,
  -- whoever brings the shuttles) — a percentage off the court+shuttle cost
  -- before the flat +10 buffer below, not off the final payable amount.
  discount_percent numeric(5, 2) not null default 0 check (discount_percent >= 0 and discount_percent <= 100),
  -- Server-managed (recomputePlayerGameCounts in src/app/actions.ts), not
  -- directly editable: this player's even share of covering everyone
  -- else's discount_percent this session, in pesos, added on top of their
  -- own court+shuttle cost. Always 0 for a player who has a discount of
  -- their own — the cost only spreads across players without one.
  surcharge_amount numeric(10, 2) not null default 0 check (surcharge_amount >= 0),
  payable numeric(10, 2) generated always as (
    case when (court_share + shuttle_share + surcharge_amount) = 0 then 0
         else ceil(((court_share + shuttle_share) * (1 - discount_percent / 100.0) + surcharge_amount) / 10.0) * 10 + 10
    end
  ) stored,
  -- null = unpaid; otherwise the method used
  payment_method text check (payment_method is null or payment_method in ('Cash', 'Gcash')),
  -- set from the "Done" toggle on a player row once someone's finished
  -- playing for the day; excludes them from the New Game player picker
  -- while keeping their games/payment record intact.
  done_for_session boolean not null default false,
  created_at timestamptz not null default now(),
  unique (session_id, player_id)
);

-- safe to re-run against a database created before done_for_session existed
alter table player_sessions add column if not exists done_for_session boolean not null default false;

-- safe to re-run against a database created before discount_percent existed
-- — a generated column's formula can't be altered in place, so this drops
-- and recreates `payable` with the discount folded in. Harmless to re-run:
-- the recomputed value is identical to what's already stored.
alter table player_sessions add column if not exists discount_percent numeric(5, 2) not null default 0
  check (discount_percent >= 0 and discount_percent <= 100);

-- safe to re-run against a database created before surcharge_amount existed
alter table player_sessions add column if not exists surcharge_amount numeric(10, 2) not null default 0;
alter table player_sessions drop constraint if exists player_sessions_surcharge_amount_check;
alter table player_sessions add constraint player_sessions_surcharge_amount_check check (surcharge_amount >= 0);

alter table player_sessions drop column if exists payable;
alter table player_sessions add column payable numeric(10, 2) generated always as (
  case when (court_share + shuttle_share + surcharge_amount) = 0 then 0
       else ceil(((court_share + shuttle_share) * (1 - discount_percent / 100.0) + surcharge_amount) / 10.0) * 10 + 10
  end
) stored;

-- ---------------------------------------------------------------------------
-- app_settings   (was: AppSheet "Home" table, plus QR config)
-- Single-row settings table: display title and the payment QR image.
-- Rates now live per-session above, not here.
-- ---------------------------------------------------------------------------
create table if not exists app_settings (
  id integer primary key default 1 check (id = 1), -- enforce a single row
  display_title text not null default 'Sat Games',
  payment_qr_url text,
  app_icon_url text,
  updated_at timestamptz not null default now()
);

-- safe to re-run against a database created before app_icon_url existed
alter table app_settings add column if not exists app_icon_url text;

insert into app_settings (id) values (1)
  on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Public queue viewing + game requests
-- The public /join page lets anyone with a session's 6-digit join_code see
-- a live view of who's playing now, who's up next, and any pending "set
-- requests" — no login, no registration required to just look. (An earlier
-- version had visitors submit a "join request" into a join_requests table
-- for the queue master to approve — dropped below. A viewer asking to be
-- added to the roster is still a manual queue-master job, via New
-- Player.) These functions are the ONLY access an anonymous visitor has —
-- security definer runs them with the function owner's privileges,
-- bypassing RLS *only* for the exact columns/operation each one does,
-- never open read/write access to the sessions/games/players tables
-- themselves (which also hold cost/fee data and far more than a viewer
-- needs).
--
-- request_game is the one WRITE anon gets: a player who's checking the
-- queue can request a set (pick who's playing, from that session's own
-- roster) instead of asking the queue master to type it in. It lands as a
-- game row with status 'Requested' — visible in the *queue master's* Games
-- Queued list same as any other queued game, distinguished by that status,
-- until approved (moved to 'Queued') or edited/declined there. This is
-- deliberately different from the old join_requests approval flow: nobody
-- is being added to or removed from the roster here, so there's no
-- identity/authorization question to resolve, just "does the queue master
-- want to run this match" — same as always, just pre-filled.
-- ---------------------------------------------------------------------------

-- join_requests' whole job (approve/decline) doesn't exist anymore now that
-- /join is view-only for joining — safe to re-run, a no-op once it's
-- already dropped.
drop table if exists join_requests;

-- Turns a join_code into a session_id (plus just enough to show "Queue for
-- Sat, Oct 4") without granting anon any read access to the sessions table
-- itself.
create or replace function find_session_by_join_code(code text)
returns table (id uuid, session_date date, title text)
language sql
security definer
set search_path = public
as $$
  select id, session_date, title from sessions where join_code = code and status = 'Open';
$$;

grant execute on function find_session_by_join_code(text) to anon, authenticated;

-- The roster a player picks from when requesting a set: everyone
-- registered for the session who isn't marked done_for_session, name only
-- (no costs, no payment info) — same shape the queue master's own player
-- picker offers, minus everything a viewer doesn't need.
create or replace function get_roster_by_code(code text)
returns table (player_id uuid, player_name text)
language sql
security definer
set search_path = public
as $$
  select p.id, p.name
  from player_sessions ps
  join sessions s on s.id = ps.session_id
  join players p on p.id = ps.player_id
  where s.join_code = code
    and s.status = 'Open'
    and ps.done_for_session = false
  order by p.name;
$$;

grant execute on function get_roster_by_code(text) to anon, authenticated;

-- The queue itself: every not-yet-finished game (Requested, Queued, or
-- Ongoing) for the session matching that code, with player *names* only —
-- no ids, no costs, nothing about players who aren't in one of those games.
-- Queued/Ongoing rows are always included (that's the actual queue — fair
-- game for anyone to see). A 'Requested' row is different: it's not
-- approved yet, so it's only included when it's the *caller's own*
-- request — g.requester_token (set by request_game below, from an opaque
-- per-device id the client keeps in localStorage) has to match the
-- viewer_token this call was made with. A request with no requester_token
-- at all (shouldn't normally happen, but covers old rows/a client that
-- failed to generate one) never matches anyone and just stays invisible
-- here — the queue master still sees it fine, that's a separate,
-- authenticated read straight off the table, not this function.
-- `create or replace` can't change a function's return type or remove a
-- parameter — drop first so re-running this file against a database with
-- an older version doesn't error.
drop function if exists get_queue_by_code(text);
drop function if exists get_queue_by_code(text, text);

create function get_queue_by_code(code text, viewer_token text default null)
returns table (
  game_number integer,
  status text,
  player1_name text,
  player2_name text,
  player3_name text,
  player4_name text,
  requested_by text
)
language sql
security definer
set search_path = public
as $$
  select g.game_number, g.status, p1.name, p2.name, p3.name, p4.name, g.requested_by
  from games g
  join sessions s on s.id = g.session_id
  left join players p1 on p1.id = g.player1_id
  left join players p2 on p2.id = g.player2_id
  left join players p3 on p3.id = g.player3_id
  left join players p4 on p4.id = g.player4_id
  where s.join_code = code
    and s.status = 'Open'
    and (
      g.status in ('Queued', 'Ongoing')
      or (g.status = 'Requested' and g.requester_token is not null and g.requester_token = viewer_token)
    )
  order by g.game_number;
$$;

grant execute on function get_queue_by_code(text, text) to anon, authenticated;

-- Submit a "request a set" from the public /join page. player_ids is 1-4
-- player ids (order matters — same team split as everywhere else: 1st &
-- 2nd = team1, 3rd & 4th = team2), each of which MUST already be on that
-- session's roster (checked below) — an anonymous caller can pass any uuid
-- it wants, so this is the one thing that can't just be trusted from the
-- client the way the rest of this function's inputs are. requested_by is
-- an optional free-text name (who to credit/ask), stored as-is, not
-- matched against the roster. requester_token is the same opaque per-device
-- id get_queue_by_code above filters on, so this player's own pending
-- request is the only one their /join view will show them.
--
-- Lands the new row as status 'Requested' — everything else (game_number,
-- game_date) mirrors what the queue master's own createGame server action
-- does, so a requested game slots into the same numbering as one they
-- added themselves.
-- Postgres identifies a function by name + parameter TYPES, so adding a
-- new parameter (even with a default) doesn't let `create or replace`
-- update the existing 3-arg version in place — it silently creates a
-- second overload instead, and PostgREST's RPC dispatch then can't tell
-- which one a named-argument call means. Drop the old signature first so
-- re-running this file against an already-migrated database doesn't leave
-- that stale overload behind.
drop function if exists request_game(text, uuid[], text);

create or replace function request_game(
  code text,
  player_ids uuid[],
  requested_by text default null,
  requester_token text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  target_session_id uuid;
  target_session_date date;
  registered_count integer;
  distinct_requested integer;
  next_game_number integer;
  p1 uuid;
  p2 uuid;
  p3 uuid;
  p4 uuid;
begin
  select id, session_date into target_session_id, target_session_date
  from sessions
  where join_code = code and status = 'Open';

  if target_session_id is null then
    raise exception 'That code doesn''t match an open session.';
  end if;

  player_ids := array_remove(player_ids, null);
  distinct_requested := (select count(distinct x) from unnest(player_ids) x);
  if distinct_requested = 0 then
    raise exception 'Pick at least one player.';
  end if;
  if distinct_requested > 4 then
    raise exception 'A set is at most 4 players.';
  end if;

  select count(*) into registered_count
  from player_sessions
  where session_id = target_session_id and player_id = any(player_ids);
  if registered_count <> distinct_requested then
    raise exception 'One or more players aren''t registered for this session.';
  end if;

  p1 := player_ids[1];
  p2 := player_ids[2];
  p3 := player_ids[3];
  p4 := player_ids[4];

  select coalesce(max(game_number), 0) + 1 into next_game_number
  from games
  where session_id = target_session_id;

  insert into games (session_id, game_number, game_date, status, player1_id, player2_id, player3_id, player4_id, requested_by, requester_token)
  values (target_session_id, next_game_number, target_session_date, 'Requested', p1, p2, p3, p4, nullif(trim(requested_by), ''), nullif(trim(requester_token), ''));

  return next_game_number;
end;
$$;

grant execute on function request_game(text, uuid[], text, text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- The app now sits behind a login (Supabase Auth + a proxy/middleware
-- redirect), so every table requires a signed-in user for every operation —
-- there's no per-user data ownership here (it's one shared group app), just
-- "must be logged in." If you're running this against a fresh database
-- before setting up auth, these policies still work: an anon (logged-out)
-- request is simply refused until you sign in.
-- ---------------------------------------------------------------------------
alter table players enable row level security;
alter table sessions enable row level security;
alter table games enable row level security;
alter table player_sessions enable row level security;
alter table app_settings enable row level security;

drop policy if exists "Allow all (temporary, no auth yet)" on players;
drop policy if exists "Allow all (temporary, no auth yet)" on sessions;
drop policy if exists "Allow all (temporary, no auth yet)" on games;
drop policy if exists "Allow all (temporary, no auth yet)" on player_sessions;
drop policy if exists "Allow all (temporary, no auth yet)" on app_settings;
drop policy if exists "Require login" on players;
drop policy if exists "Require login" on sessions;
drop policy if exists "Require login" on games;
drop policy if exists "Require login" on player_sessions;
drop policy if exists "Require login" on app_settings;

create policy "Require login" on players for all using (auth.uid() is not null) with check (auth.uid() is not null);
create policy "Require login" on sessions for all using (auth.uid() is not null) with check (auth.uid() is not null);
create policy "Require login" on games for all using (auth.uid() is not null) with check (auth.uid() is not null);
create policy "Require login" on player_sessions for all using (auth.uid() is not null) with check (auth.uid() is not null);
create policy "Require login" on app_settings for all using (auth.uid() is not null) with check (auth.uid() is not null);

-- ---------------------------------------------------------------------------
-- Realtime
-- Lets every open tab/device pick up a change (add/edit/delete) the moment
-- it happens anywhere else, instead of needing a manual refresh. See
-- enable_realtime.sql for the standalone version of this block (run that
-- one instead if you're applying this to an existing live database).
-- ---------------------------------------------------------------------------
do $$
begin
  alter publication supabase_realtime add table players;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table sessions;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table games;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table player_sessions;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table app_settings;
exception when duplicate_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- storage   (uploaded images — the app icon and the payment QR code, set
-- from the app's Settings popup instead of pasting a URL by hand)
-- One public bucket. Reads stay public (so <img src="..."> tags just work
-- without signed URLs — these are non-sensitive display images), but
-- writes require a signed-in user, same as the tables above.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
  values ('assets', 'assets', true)
  on conflict (id) do nothing;

drop policy if exists "Allow all read (assets)" on storage.objects;
drop policy if exists "Allow all insert (assets)" on storage.objects;
drop policy if exists "Allow all update (assets)" on storage.objects;
drop policy if exists "Allow all delete (assets)" on storage.objects;
-- also drop the *current* names this block itself creates — without this,
-- re-running the script a second time (e.g. this migration, on a database
-- that already had enable_auth_policies.sql applied once) fails with
-- "policy ... already exists" instead of being a no-op like every other
-- policy in this file.
drop policy if exists "Require login to write (assets)" on storage.objects;
drop policy if exists "Require login to update (assets)" on storage.objects;
drop policy if exists "Require login to delete (assets)" on storage.objects;

create policy "Allow all read (assets)" on storage.objects
  for select using (bucket_id = 'assets');
create policy "Require login to write (assets)" on storage.objects
  for insert with check (bucket_id = 'assets' and auth.uid() is not null);
create policy "Require login to update (assets)" on storage.objects
  for update using (bucket_id = 'assets' and auth.uid() is not null);
create policy "Require login to delete (assets)" on storage.objects
  for delete using (bucket_id = 'assets' and auth.uid() is not null);
